name: build
on: [push]
jobs:
  test_api:
    name: api test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm
          scan: "./APIServer"
      - run: 
          npm ci
          npm run init:test
          npm run migrate:test
      - name: Execute test
        run: 
          npm run init:test
          npm run migrate:test
          npm run ci
      - name: Publish coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
