name: build
on: [push]

jobs:
  test_api:
    name: api test
    runs-on: ubuntu-20.04
    services:
      db:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: mahjongranking
          MYSQL_PASSWORD: mahjongrankingservice001
          MYSQL_DATABASE: mahjongranking
          options: >-
            --health-cmd "mysqladmin ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        volumes:
          - ./APIServer/docker/db:/initdb.d
    env:
      DATABASE_URL: "mysql://mahjongranking:mahjongrankingservice001@localhost:3306/mahjongranking"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: ./APIServer
      - run: |
          npm run migrate:test
          npm ci
        working-directory: "./APIServer"
      - name: Execute test
        run: |
          npm run migrate:test
          npm run ci
        working-directory: "./APIServer"
      - name: Publish coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
